################################################################################
# smart speaker
#
# docker-compose -f smart-speaker.yml up --build
################################################################################

version: '3.7'

services:
  smart-speaker:
    image: bitshift/smart-speaker
    container_name: smart-speaker
    user: 1000:1000
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    privileged: true
    restart: unless-stopped
    network_mode: host
    #entrypoint: ['ash']
    tty: true
    volumes:
      #- /run/user/1000/pipewire-0:/tmp/pipewire-0
      #- /var/run/dbus:/var/run/dbus # shared bluetooth
      - /etc/localtime:/etc/localtime:ro